# Generated by Django 6.1 on 2026-09-10 01:10

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0005_book_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='taste_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
