# Generated by Django 6.1 on 2026-08-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ucsd_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('google_books_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('author', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('published_year', models.PositiveIntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, db_index=True, max_length=32)),
                ('avg_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('ratings_count', models.PositiveIntegerField(default=0)),
                ('enriched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
