# Generated by Django 6.1 on 2026-08-09 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_seed_avg_rating_book_seed_ratings_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='canonical_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_editions', to='books.book'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genres',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
