# Generated by Django 6.1 on 2026-08-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_canonical_book_alter_book_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='similar_books',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
