# Generated by Django 6.1 on 2026-08-21 23:57

import pgvector.django.vector
from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_similar_books'),
    ]

    operations = [
        VectorExtension(),
        migrations.AddField(
            model_name='book',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]