# Generated by Django 6.1 on 2026-09-10 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='similar_books',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
